<?php
return array(
	'hvac-replacement-newark-de' => array(
		'slug' => 'hvac-replacement-newark-de', 'template' => 'service', 'service_type' => 'HVAC Replacement',
		'title' => 'HVAC Replacement Newark, DE | New HVAC System',
		'meta' => 'HVAC replacement in Newark, DE for whole-home heating and cooling systems. Matched equipment, duct evaluation, financing, and permit-ready installs.',
		'h1' => 'HVAC Replacement in Newark, DE — New Systems, Honest Scope',
		'hero_sub' => 'Replace the full heating and cooling plant when both sides are tired. One project, one permit path, one walkthrough — not two emergency failures a year apart.',
		'crumbs' => nhp_crumbs( 'HVAC Replacement', 'hvac-replacement-newark-de' ),
		'intro' => array(
			'HVAC replacement Newark DE is the highest-ticket residential job on this site. Homes built around 1978 with 15–20 year equipment lives are squarely in the window. A condenser that dies in July and a furnace that dies the next January is the expensive way to modernize.',
			'We quote matched systems: outdoor unit, indoor coil, furnace or air handler, thermostat, and the duct or electrical work required for the system to actually hit its rated efficiency.',
		),
		'symptoms_title' => 'Signs you need a full system replacement',
		'symptoms' => array('Both furnace and AC are 12+ years old','Repair quotes stacking twice in 24 months','Comfort problems in every season','Ducts crushed, disconnected, or never sealed','Interest in a heat pump conversion at the same time'),
		'body' => array(
			array('h' => 'What a Newark replacement includes','p' => array('Load calculation, equipment selection, removal, new pad or indoor cabinet work, line set evaluation, condensate, electrical whip and disconnect, thermostat, startup, and homeowner orientation. If return air is starving a 1990s blower, we price duct corrections as optional line items — not hidden change orders on install day.')),
			array('h' => 'Brands','p' => array('Carrier, Trane, Lennox, Rheem, Goodman, Amana, American Standard, York, Bosch, Bryant, and Ruud are all in play depending on parts availability and your efficiency target.')),
		),
		'cost' => array('h' => 'HVAC system cost in Newark','p' => array('Whole-home replacements vary widely. Think in terms of several thousand dollars on the low end for a simple swap and well into five figures when ducts, electrical panels, and dual-fuel heat pumps enter the scope. Use the cost guide for ranges, then get a site visit.')),
		'faqs' => array(
			array('q' => 'How long does HVAC replacement take?','a' => 'One to three days for most Newark houses after equipment is on site. Panel upgrades add time.'),
			array('q' => 'Can I stay in the house?','a' => 'Usually yes. There will be hours without heat or AC during changeover. We plan around weather when we can.'),
		),
		'related' => array(
			nhp_rel('ac-installation-newark-de','AC Installation','Cooling-only replacements.'),
			nhp_rel('furnace-installation-newark-de','Furnace Installation','Heating-only replacements.'),
			nhp_rel('hvac-financing-newark-de','Financing','Payment options.'),
		),
	),
	'hvac-maintenance-newark-de' => array(
		'slug' => 'hvac-maintenance-newark-de', 'template' => 'service', 'service_type' => 'HVAC Maintenance',
		'title' => 'HVAC Maintenance Newark, DE | Tune-Ups',
		'meta' => 'HVAC maintenance and tune-ups in Newark, DE. Spring AC service and fall furnace inspections for 19702, 19711, 19713, and nearby.',
		'h1' => 'HVAC Maintenance in Newark, DE — Spring and Fall Tune-Ups',
		'hero_sub' => 'A $80–$200 visit in April or October is cheaper than a capacitor failure on the first 90° heat-index day or an ignitor death on a 20° night.',
		'crumbs' => nhp_crumbs( 'HVAC Maintenance', 'hvac-maintenance-newark-de' ),
		'intro' => array('Tune-ups are how Newark homeowners with 1970s duct systems and 15-year-old equipment stay off the emergency page. We do not sell a “Bouldenization”-style trademark. We sell a checklist: electrical, airflow, combustion or refrigerant temperatures, drains, filters, and safety controls.','Spring is for AC. Fall is for furnaces and heat pumps in heating mode. Doing both in one sloppy 20-minute stop is how missed flame-sensor problems show up on New Year’s Day.'),
		'symptoms_title' => 'You are overdue if',
		'symptoms' => array('No professional service in 12+ months','Filter never changed through a UD rental turnover','AC froze last summer','Furnace soot or more dust than usual','Energy bills jumped without a rate change'),
		'body' => array(
			array('h' => 'What a tune-up includes','p' => array('Filter check, coil inspection, blower cleaning as needed, condensate flush, thermostat test, amp draws, temperature split, outdoor coil rinse when appropriate, and a written list of defects. Oil systems get combustion-focused service. Heat pumps get defrost and reversing checks.')),
			array('h' => 'Service plans','p' => array('Ask about twice-yearly reminders. Plans only make sense if visits actually happen — we will not enroll you in a phantom membership.')),
		),
		'cost' => array('h' => 'Tune-up pricing','p' => array('Most Newark maintenance visits are about $80–$200 depending on system type and whether two seasons are combined. Repairs found during the visit are quoted separately.')),
		'faqs' => array(
			array('q' => 'When should Newark homeowners book AC maintenance?','a' => 'March–May, before the first heat wave fills the emergency board.'),
			array('q' => 'When should I book furnace maintenance?','a' => 'September–November, before overnight lows settle in the 30s.'),
		),
		'related' => array(
			nhp_rel('blog/spring-hvac-checklist-newark','Spring Checklist','DIY plus pro items.'),
			nhp_rel('blog/fall-furnace-maintenance-newark','Fall Furnace Guide','Before the first freeze.'),
			nhp_rel('ac-repair-newark-de','AC Repair','If you already have a symptom.'),
		),
	),
	'ductless-mini-split-newark-de' => array(
		'slug' => 'ductless-mini-split-newark-de', 'template' => 'service', 'service_type' => 'Ductless Mini Split',
		'title' => 'Ductless Mini Split Newark, DE | Mini Split Installation',
		'meta' => 'Ductless mini split installation and repair in Newark, DE for additions, rentals, and rooms with no ducts.',
		'h1' => 'Ductless Mini Splits in Newark, DE',
		'hero_sub' => 'Heat and cool a sunroom, garage conversion, or UD-area rental bedroom without ripping open every ceiling.',
		'crumbs' => nhp_crumbs( 'Ductless Mini Split', 'ductless-mini-split-newark-de' ),
		'intro' => array('Mini splits solve Newark problems that ducts cannot: finished third floors, enclosed porches, in-law suites, and older homes where adding a trunk would destroy plaster. They are also a practical heat-pump path for homes stuck on oil with no easy gas conversion.','We install single-zone and multi-zone systems and repair heads that freeze, drip, or stop responding to the remote.'),
		'symptoms' => array('One room never matches the rest of the house','Addition built without extending ducts','Window units doing too much work','Interest in a heat pump without a full duct redesign'),
		'body' => array(
			array('h' => 'Installation notes for New Castle County','p' => array('Line-set length, condensate routing, and winter defrost clearance matter. A head over a UD rental couch that drips in August is a callback we prefer to design out. Outdoor units need snow and mower clearance.')),
			array('h' => 'Rebates','p' => array('Energize Delaware lists mini-split heat pump tiers (roughly $550–$1,700 on the standard path depending on efficiency, plus amounts per additional indoor unit) inside whole-home caps. Confirm current rules and the required audit path before you buy.')),
		),
		'cost' => array('h' => 'Mini split cost in Newark','p' => array('Single-zone installs often start in the $3,000–$8,000 range depending on capacity, line-set difficulty, and electrical work. Multi-zone is more. Repair visits follow standard diagnostic rates.')),
		'faqs' => array(
			array('q' => 'Can mini splits heat a Newark winter?','a' => 'Cold-climate models can. Cheap cooling-only units cannot. We spec heating-capable equipment when that is the job.'),
			array('q' => 'Are they noisy?','a' => 'Indoor heads should be a quiet whoosh on low. Rattle usually means a mount or blower issue we can service.'),
		),
		'related' => array(
			nhp_rel('heat-pump-installation-newark-de','Heat Pump Installation','Ducted heat pump alternative.'),
			nhp_rel('indoor-air-quality-newark-de','Indoor Air Quality','Filtration still matters with ductless.'),
		),
	),
	'indoor-air-quality-newark-de' => array(
		'slug' => 'indoor-air-quality-newark-de', 'template' => 'service', 'service_type' => 'Indoor Air Quality',
		'title' => 'Indoor Air Quality Newark, DE | Purifiers, Humidifiers, Dehumidifiers',
		'meta' => 'Indoor air quality services in Newark, DE: whole-home filtration, humidifiers for dry winters, and dehumidifiers for sticky summers.',
		'h1' => 'Indoor Air Quality in Newark, DE Homes',
		'hero_sub' => 'Older ducts, pollen, pets, and a climate that swings from dry heat to swampy AC season — IAQ is not a luxury add-on in New Castle County.',
		'crumbs' => nhp_crumbs( 'Indoor Air Quality', 'indoor-air-quality-newark-de' ),
		'intro' => array('Newark’s older housing (median build ~1978) means aged ductwork, dust, and sometimes oil-heat residue. Summers are humid enough that indoor RH regularly climbs past comfort. Winters with the furnace running dry out sinuses and wood floors. University-area households also deal with high occupancy and allergen load.','We install and service whole-home filters, humidifiers, dehumidifiers, and discuss UV or media cabinets only where they solve a named problem.'),
		'symptoms' => array('Musty HVAC smell','Static shocks and dry air in January','Windows sweating in July','Allergy flare-ups at home','Visible dust right after the system runs'),
		'body' => array(
			array('h' => 'Humidity control','p' => array('A dehumidifier tied into the return or a correctly sized AC that actually runs long enough to strip moisture will do more than a portable unit in one hallway. Whole-home humidifiers help on gas-heat winters if the water and drain are done right.')),
			array('h' => 'Filtration vs. duct cleaning','p' => array('A high-MERV filter on a furnace that cannot pull air is a new problem. We check static pressure before selling a hospital-grade cabinet. Duct cleaning is a separate service when debris or biological growth is actually present — not a scheduled upsell.')),
		),
		'cost' => array('h' => 'IAQ project ranges','p' => array('Many whole-home IAQ add-ons land around $500–$3,000 depending on whether you need a humidifier, dehumidifier, or media filter. Portable units are cheaper and sometimes enough for a single UD apartment.')),
		'faqs' => array(
			array('q' => 'Will an air purifier fix Newark humidity?','a' => 'No. Purifiers move particles. Humidity needs dehumidification or a properly running AC.'),
			array('q' => 'Do I need duct cleaning or a better filter?','a' => 'Often a better filter and a sealed return. Cleaning helps when ducts are contaminated or packed with debris. We inspect instead of guessing.'),
		),
		'related' => array(
			nhp_rel('duct-cleaning-newark-de','Duct Cleaning','When debris is the issue.'),
			nhp_rel('hvac-maintenance-newark-de','Maintenance','Filters and coils first.'),
		),
	),
	'duct-cleaning-newark-de' => array(
		'slug' => 'duct-cleaning-newark-de', 'template' => 'service', 'service_type' => 'Duct Cleaning',
		'title' => 'Duct Cleaning Newark, DE | Air Duct Cleaning',
		'meta' => 'Air duct cleaning in Newark, DE for older duct systems, renovations, and homes with excess dust or odors.',
		'h1' => 'Air Duct Cleaning in Newark, DE',
		'hero_sub' => 'For 1970s trunks that have never been opened, post-renovation dust, or a system that blows grit — not a twice-a-year ritual.',
		'crumbs' => nhp_crumbs( 'Duct Cleaning', 'duct-cleaning-newark-de' ),
		'intro' => array('Duct cleaning Newark DE is searched because older homes and pet households feel dusty. NADCA-style cleaning helps when there is a real load of debris, rodents, or construction dust. It does not magically cut 30% off a Delmarva Power bill. We will decline a cleaning if the honest fix is sealing leaks or replacing collapsing flex.'),
		'symptoms' => array('Dust puffs from registers at startup','Visible debris in trunks','Musty odor from returns','After drywall or floor sanding','Pest evidence in ductwork'),
		'body' => array(array('h' => 'How we approach ducts in Newark','p' => array('Inspect, photograph where possible, contain, agitate, vacuum, and check that the system still moves air. If you need ductwork repair or replacement, we say that before selling a cleaning on a disconnected trunk in a crawlspace.'))),
		'cost' => array('h' => 'Duct cleaning cost','p' => array('Many whole-home cleanings in this market fall around $300–$600, more for large or contaminated systems. Repair and sealing are quoted separately.')),
		'faqs' => array(array('q' => 'How often should Newark homes clean ducts?','a' => 'Not on a calendar for its own sake. After renovations, pests, or when inspection shows a load. Filters matter every 1–3 months.')),
		'related' => array(nhp_rel('ductwork-repair-newark-de','Ductwork Repair','Sealing and replacement.'), nhp_rel('indoor-air-quality-newark-de','IAQ','Filters and humidity.')),
	),
	'ductwork-repair-newark-de' => array(
		'slug' => 'ductwork-repair-newark-de', 'template' => 'service', 'service_type' => 'Ductwork Repair',
		'title' => 'Ductwork Repair Newark, DE',
		'meta' => 'Ductwork repair, sealing, and installation in Newark, DE for leaky 1970s systems and additions.',
		'h1' => 'Ductwork Repair in Newark, DE',
		'hero_sub' => 'If rooms never even out, the problem may be the trunks — not the brand on the condenser.',
		'crumbs' => nhp_crumbs( 'Ductwork Repair', 'ductwork-repair-newark-de' ),
		'intro' => array('Median 1978 construction means original sheet metal and later cheap flex. Returns that dump into a crawlspace, crushed lines in attics, and disconnected joints after a renovation are routine in Newark, Brookside, and Ogletown. We repair, seal, and replace sections rather than blaming the thermostat.'),
		'symptoms' => array('Some rooms never cool or heat','Whistling at takeoffs','High bills with weak airflow','Flex hanging or kinked','New addition with a single leftover register'),
		'body' => array(array('h' => 'Repair vs. new runs','p' => array('Mastic and properly sealed joints fix a lot. Collapsed flex and undersized returns need new metal or quality flex with correct radius. We measure static pressure so a “high efficiency” furnace is not strangled.'))),
		'cost' => array('h' => 'Ductwork pricing','p' => array('Small sealing jobs can start a few hundred dollars. New runs and major redesigns run into the thousands. Quotes follow inspection.')),
		'faqs' => array(array('q' => 'Can you add ducts for a basement finish?','a' => 'Often yes, if the equipment has capacity. Sometimes a mini split is cleaner. We will say which.')),
		'related' => array(nhp_rel('hvac-replacement-newark-de','HVAC Replacement','When equipment and ducts both fail.'), nhp_rel('duct-cleaning-newark-de','Duct Cleaning','When debris is the issue.')),
	),
	'commercial-hvac-newark-de' => array(
		'slug' => 'commercial-hvac-newark-de', 'template' => 'service', 'service_type' => 'Commercial HVAC',
		'title' => 'Commercial HVAC Newark, DE',
		'meta' => 'Commercial HVAC repair and service in Newark, DE for offices, retail, and light commercial near Christiana and the I-95 corridor.',
		'h1' => 'Commercial HVAC in Newark, DE',
		'hero_sub' => 'Rooftop units, split systems, and after-hours service for small commercial spaces — secondary to our residential focus, available where we can staff it well.',
		'crumbs' => nhp_crumbs( 'Commercial HVAC', 'commercial-hvac-newark-de' ),
		'intro' => array('Commercial HVAC Newark DE is a real but secondary market here. Christiana Hospital’s orbit, office parks, and retail along Ogletown Road create rooftop and split-system demand. We take small commercial jobs we can serve at residential-quality communication: a named contact, a quoted repair, and a time window that respects your hours.'),
		'symptoms' => array('RTU down on a retail roof','Office suite with no cooling on one floor','After-hours restaurant heat complaints','Maintenance contracts for a small portfolio'),
		'body' => array(array('h' => 'What we are not','p' => array('We are not positioning as a 600-person regional giant. Large campus BAS projects belong with firms built for that. Independent restaurants, offices, and light industrial near 19702/19713 are the fit.'))),
		'cost' => array('h' => 'Commercial tickets','p' => array('Jobs range from a few hundred dollars for a contactor to many thousands for a rooftop replacement. Site visit required.')),
		'faqs' => array(array('q' => 'Do you offer planned maintenance for businesses?','a' => 'Yes, for small portfolios we can actually reach on a schedule. Ask on the contact form.')),
		'related' => array(nhp_rel('emergency-hvac-newark-de','Emergency HVAC','After-hours failures.'), nhp_rel('contact','Contact','Commercial intake.')),
	),
	'hvac-financing-newark-de' => array(
		'slug' => 'hvac-financing-newark-de', 'template' => 'service', 'service_type' => 'HVAC Financing',
		'title' => 'HVAC Financing Newark, DE | Payment Plans',
		'meta' => 'HVAC financing in Newark, DE for replacements and high-ticket repairs. Ask about payment plans on qualifying installations.',
		'h1' => 'HVAC Financing in Newark, DE',
		'hero_sub' => 'A failed condenser in July should not require a cash-only decision. Ask about financing on qualifying replacements.',
		'crumbs' => nhp_crumbs( 'HVAC Financing', 'hvac-financing-newark-de' ),
		'intro' => array('Every serious Newark competitor mentions financing because replacements cost thousands. We do too — without pretending a specific lender is already signed if the operating contractor still needs to connect GreenSky, Synchrony, or another program. When you request a replacement quote, ask for current financing options. Decisions are often fast; approval is never guaranteed.'),
		'symptoms_title' => 'Financing is commonly used for',
		'symptoms' => array('AC or furnace replacement','Full HVAC system changeouts','Heat pump conversions','High-cost repairs you still choose over replacement'),
		'body' => array(
			array('h' => 'How it works','p' => array('Get the equipment quote first. If you want to finance, we start the application with the live lender partner. You will see term, APR, and whether a promotional period applies before you sign. Repairs under a few hundred dollars are usually cash or card.')),
			array('h' => 'Rebates are not financing','p' => array('Energize Delaware incentives, if you qualify, reduce project cost. They are not a loan. Stacking rules depend on the program year — we will not promise a stack we have not verified for your job.')),
		),
		'cost' => array('h' => 'What you should compare','p' => array('APR, term, origination fees, and whether paying cash with a rebate is cheaper than a long loan. We will run the numbers beside the equipment quote.')),
		'faqs' => array(
			array('q' => 'Can I finance a repair?','a' => 'Small repairs are typically paid at completion. Larger jobs and replacements are the usual financing candidates.'),
			array('q' => 'Does financing delay installation?','a' => 'Usually by hours or a day, not weeks, once documents are complete.'),
		),
		'related' => array(nhp_rel('hvac-cost-guide-newark-de','Cost Guide','See typical project ranges.'), nhp_rel('hvac-replacement-newark-de','HVAC Replacement','What financing usually covers.')),
	),
	'boiler-repair-newark-de' => array(
		'slug' => 'boiler-repair-newark-de', 'template' => 'service', 'service_type' => 'Boiler Repair',
		'title' => 'Boiler Repair Newark, DE',
		'meta' => 'Boiler repair and service in Newark, DE for hydronic and oil-fired boilers in older homes.',
		'h1' => 'Boiler Repair in Newark, DE',
		'hero_sub' => 'Cast-iron and oil boilers still heat a slice of older New Castle County housing. When they leak, lock out, or go cold, call.',
		'crumbs' => nhp_crumbs( 'Boiler Repair', 'boiler-repair-newark-de' ),
		'intro' => array('Boiler repair Newark DE is a smaller cluster than forced-air furnaces but it matters for oil-heated and hydronic homes. Circ pumps, expansion tanks, zone valves, and ignition failures show up on the coldest days. We repair what is safe and quote replacement when the vessel is rusted through.'),
		'symptoms' => array('No heat at the radiators','Gurgling or kettling','Water on the floor around the boiler','Pressure relief dripping','One zone dead, others hot'),
		'body' => array(array('h' => 'Oil and gas boilers','p' => array('We service residential boilers. Commercial steam plants and large mechanical rooms are a different bid. If your home also needs domestic hot water from the same boiler, we check that loop too.'))),
		'cost' => array('h' => 'Boiler repair cost','p' => array('Many repairs overlap furnace ranges. Vessel replacement is a major project. Energize Delaware lists high-AFUE boiler incentives on the Home Performance menu for qualifying equipment.')),
		'faqs' => array(array('q' => 'Can you convert a boiler house to a furnace or heat pump?','a' => 'Sometimes. Distribution (radiators vs. ducts) drives the answer. Site visit required.')),
		'related' => array(nhp_rel('furnace-repair-newark-de','Furnace Repair','Forced-air heat.'), nhp_rel('emergency-hvac-newark-de','Emergency','No-heat dispatch.')),
	),
	'thermostat-installation-newark-de' => array(
		'slug' => 'thermostat-installation-newark-de', 'template' => 'service', 'service_type' => 'Thermostat Installation',
		'title' => 'Thermostat Installation Newark, DE | Smart Thermostats',
		'meta' => 'Thermostat repair and smart thermostat installation in Newark, DE, including C-wire and heat-pump changeover setup.',
		'h1' => 'Thermostat Installation in Newark, DE',
		'hero_sub' => 'A $25 Walmart thermostat wired wrong on a heat pump is a winter emergency. We install and configure the control to match the equipment.',
		'crumbs' => nhp_crumbs( 'Thermostats', 'thermostat-installation-newark-de' ),
		'intro' => array('Thermostat repair Newark DE is often DIY — until it is a heat pump in emergency heat, a missing C-wire, or a dual-fuel changeover set 20 degrees too high. We install smart thermostats when the transformer and wiring support them, and we stop short of forcing a Wi-Fi device on a 2-wire millivolt gas heater that cannot run it.'),
		'symptoms' => array('Blank thermostat','System ignores setpoint','Heat pump stuck on auxiliary','Wi-Fi thermostat dropping offline','After a DIY swap, nothing works'),
		'body' => array(array('h' => 'Smart thermostats and Delmarva programs','p' => array('Some utility programs rebate professionally installed ENERGY STAR thermostats. Eligibility depends on your utility and program year. We will not quote a Maryland Delmarva rebate on a Delaware meter without checking.'))),
		'cost' => array('h' => 'Typical cost','p' => array('Thermostat replacement often falls around $100–$400 including a standard device and labor. Premium smart stats and wiring upgrades cost more.')),
		'faqs' => array(array('q' => 'Can you install a Nest or similar on my furnace?','a' => 'Often, if there is a C-wire or we add a compatible adapter. Heat pumps need the correct O/B configuration — that is where DIY fails.')),
		'related' => array(nhp_rel('hvac-diagnostics-newark-de','Diagnostics','When the symptom is not the thermostat.'), nhp_rel('heat-pump-repair-newark-de','Heat Pump Repair','Changeover issues.')),
	),
	'hvac-diagnostics-newark-de' => array(
		'slug' => 'hvac-diagnostics-newark-de', 'template' => 'service', 'service_type' => 'HVAC Diagnostics',
		'title' => 'HVAC Diagnostics Newark, DE | Troubleshooting',
		'meta' => 'HVAC troubleshooting in Newark, DE for noises, smells, short cycling, and systems that run without conditioning the house.',
		'h1' => 'HVAC Diagnostics in Newark, DE — What’s Wrong With My System?',
		'hero_sub' => 'Not every problem is “add refrigerant.” We test, then we quote. Symptom-based calls welcome.',
		'crumbs' => nhp_crumbs( 'HVAC Diagnostics', 'hvac-diagnostics-newark-de' ),
		'intro' => array('This page exists because competitors leave troubleshooting thin. If your HVAC is making a loud noise, smelling musty or burning, leaking water, blowing hot air in summer, or short cycling, start here — then call. We would rather diagnose than guess from a keyword.'),
		'symptoms' => array('HVAC making loud noise','Burning or musty smell','HVAC leaking water','AC freezing up','Short cycling','House not heating or cooling evenly'),
		'body' => array(
			array('h' => 'Noise','p' => array('Squeal often means a belt or blower bearing. Rattle can be a debris fan cage. Bang at ignition on a furnace can be delayed ignition — a safety issue, not a “normal old furnace sound.”')),
			array('h' => 'Smell','p' => array('Musty: coils and drain pans. Burning dust at first fall startup can be normal for a minute. Persistent electrical or fuel smell is an emergency — leave if it is gas, then call.')),
			array('h' => 'Water','p' => array('Clogged condensate in Newark summers is common. A cracked drain pan or failed pump soaks closets and ceilings. Turn the system off if water is actively pooling and call.')),
		),
		'cost' => array('h' => 'Diagnostic fee','p' => array('You pay a diagnostic/trip that is typically applied toward the repair if you approve it the same visit. Exact fee is confirmed when you book.')),
		'faqs' => array(array('q' => 'Can you tell me the problem over the phone?','a' => 'We can rule out thermostat batteries and tripped breakers. Anything else needs tools on site.')),
		'related' => array(nhp_rel('ac-repair-newark-de','AC Repair','Cooling symptoms.'), nhp_rel('furnace-repair-newark-de','Furnace Repair','Heating symptoms.'), nhp_rel('emergency-hvac-newark-de','Emergency','Unsafe smells or no heat/cool.')),
	),
);
